deployment:
  replicas: 2
  imageVersion: IMAGE_VERSION
  imageURL: 528564298423.dkr.ecr.us-east-1.amazonaws.com/expense/dev/frontend
hpa:
  cpuUtilization: 15
tgb:
  arn: arn:aws:elasticloadbalancing:us-east-1:528564298423:targetgroup/expense-dev/c601d480468a4a17